#!/bin/bash
set -e

# openEuler arch, can be x86_64 or aarch64
export OPENEULER_ARCH="${OPENEULER_ARCH:=x86_64}"
# suseEuler arch, reserved
export SUSEEULER_ARCH=""
# openEuler version, e.g. 22.03-LTS
export OPENEULER_VERSION="${OPENEULER_VERSION:=22.03-LTS}"
# suseEuler version, reserved
export SUSEEULER_VERSION=""

# Ensure current dir is `scripts`
cd $(dirname $0)

# Shrink qcow2 image size to 8GB and convert it to RAW image
VERSION="${OPENEULER_VERSION}" ARCH="${OPENEULER_ARCH}" ./openeuler-shrink-qcow2
