#!/bin/bash
set -e

function errcho() {
   >&2 echo $@;
}

if [ -z "$VERSION" ]; then
    errcho "OPENEULER_VERSION must be set"
    exit 1
fi

PACKER_BUILDER_TYPE=${PACKER_BUILDER_TYPE:?"PACKER_BUILDER_TYPE is not set"}

echo "type: $PACKER_BUILDER_TYPE"
echo "name: $PACKER_BUILD_NAME"
echo "----------------------------------------"

yum -y update
yum -y install cloud-init cloud-utils-growpart gdisk
yum -y install vim tar make zip gzip wget git tmux \
    conntrack-tools socat iptables-services htop
# Add `apparmor=0` in kernel parameter to disable Apparmor
echo "GRUB_CMDLINE_LINUX_DEFAULT=\"apparmor=0\"" >> /etc/default/grub

if [[ ARCH == "x86_64" ]]; then
    grub2-mkconfig -o /boot/grub2/grub.cfg
elif [[ ARCH == "aarch64" ]]; then
    grub2-mkconfig -o /boot/efi/EFI/openEuler/grub.cfg
fi
