name: Build HWCloud IMS Image
on:
  workflow_dispatch:
    inputs:
      BASE_IMAGE_ID:
        description: 'HWCloud IMS Base Image ID'
        default: ''
        required: true

env:
  OPENEULER_VERSION: ${{ vars.OPENEULER_VERSION }}
  HWCLOUD_REGION: "ap-southeast-1" # HongKong

jobs:
  build-hwcloud-base:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ linux ]
        arch: [ aarch64 ] # aarch64 only for HWCloud
    permissions:
      contents: read
    env:
      ARCH: ${{ matrix.arch }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Install dependencies
        run: |
          set -x

          # The official GitHub Action runners have awscli installed by default
          if ! type aws; then
              curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
              unzip awscliv2.zip
              sudo ./aws/install
          fi
          aws --version

          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
          sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
          sudo apt-get update && sudo apt-get install packer
          packer version
          packer plugins install github.com/huaweicloud/huaweicloud

          sudo apt install -y make jq qemu-utils parted fdisk util-linux wget xz-utils kmod
      - name: openEuler ${{ env.OPENEULER_VERSION }} HWCloud ${{ env.ARCH }} Image
        env:
          HW_ACCESS_KEY: ${{ secrets.HW_ACCESS_KEY }}
          HW_SECRET_KEY: ${{ secrets.HW_SECRET_KEY }}
        run: |
          ./openeuler.sh \
              --hwcloud \
              --version ${{ env.OPENEULER_VERSION }} \
              --arch ${{ env.ARCH }} \
              --vpc ${{ vars.HW_VPC_ID }} \
              --subnet ${{ vars.HW_SUBNET_ID }} \
              --source ${{ github.event.inputs.BASE_IMAGE_ID }}
